// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABtn6qJ7rKHq2sP5WBi_e5x5FQZ88Hw2o',
    appId: '1:731857392171:web:628b6dea5324cc8123d06e',
    messagingSenderId: '731857392171',
    projectId: 'artatlas-2c109',
    authDomain: 'artatlas-2c109.firebaseapp.com',
    storageBucket: 'artatlas-2c109.firebasestorage.app',
    measurementId: 'G-8ZR7VJNXDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3LwKjrzi9baV-DIBLO5dH8zvvsD9RrU',
    appId: '1:731857392171:android:61f4595a5652966a23d06e',
    messagingSenderId: '731857392171',
    projectId: 'artatlas-2c109',
    storageBucket: 'artatlas-2c109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW8j19TP4Ef5niiRWTawkm0MLz6G1z1Po',
    appId: '1:731857392171:ios:a98c88e72f047ede23d06e',
    messagingSenderId: '731857392171',
    projectId: 'artatlas-2c109',
    storageBucket: 'artatlas-2c109.firebasestorage.app',
    iosBundleId: 'com.example.hackFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW8j19TP4Ef5niiRWTawkm0MLz6G1z1Po',
    appId: '1:731857392171:ios:a98c88e72f047ede23d06e',
    messagingSenderId: '731857392171',
    projectId: 'artatlas-2c109',
    storageBucket: 'artatlas-2c109.firebasestorage.app',
    iosBundleId: 'com.example.hackFront',
  );
}
